// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID      int64              `json:"id"`
	Front   string             `json:"front"`
	Back    string             `json:"back"`
	Know    bool               `json:"know"`
	TagsID  int32              `json:"tags_id"`
	AddTime pgtype.Timestamptz `json:"add_Time"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
