// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID      int64
	Front   string
	Back    string
	Know    bool
	AddTime pgtype.Timestamptz
}

type CardTag struct {
	CardsID int64
	TagsID  int32
}

type Tag struct {
	ID   int32
	Name string
}
