// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateCards(ctx context.Context, arg CreateCardsParams) (Card, error)
	DeleteCards(ctx context.Context, id int64) error
	GetAllCard(ctx context.Context) ([]Card, error)
	GetCard(ctx context.Context, id int64) (Card, error)
	ListCards(ctx context.Context, arg ListCardsParams) ([]Card, error)
	UpdateCards(ctx context.Context, arg UpdateCardsParams) (Card, error)
}

var _ Querier = (*Queries)(nil)
